### ISSUE TITLE
polyglot: introduce an abstraction level between the main and brokers' clients

### ISSUE THREAD

**Issue by stefanoterna** [iottly/iottly-core#10]
# Architecture

## Iottly BackendBrokerClients
Each client is basically a wrapper for the specific third party client (sleekxmpp or paho)

Currently we implement:
- `BackendBrokerClientXmpp`
- `BackendBrokerClientMqtt`

Each broker client is implemented as a `class` with the same interface:
- `__init__(params)`: a constructor taking the necessary parameters to let the inner third party client to connect to the broker
- `send_command(cmd)`: a method to send commands over the protocol

Each BackendBrokerClient 

## Iottly Polyglot
The `Polyglot` class abstracts the interaction with each BackendBrokerClient:
- once instantiated it knows the lisk of currently running BackendBrokerClient
- it knows how to route the requests to abstract methods towards the corresponding methods of each BackendBrokerClient

#### Globals
A dictionary of currently loaded BackendBrokerClients

#### Constructor
`__init__(backendbrokerclientconf: dict)`
Accepts a dict of parameters, grouped in a sub-dict for each of the required BackendBrokerClients:
```python
backendbrokerclientconf = {
  'BackendBrokerClientXmpp': {
  # place here IOTTLY_XMPP_<...> settings needed by BackendBrokerClientXmpp
  },
  'BackendBrokerClientMqtt': {
  # place here IOTTLY_MQTT_<...> settings needed by BackendBrokerClientMqtt
  }
}
```

The constructor performs the following actions:
- dinamically loads (with reflection) each module defined in the **list of keys** of the dict backendbrokerclientconf
- dinamically instantes (with reflection) each BackendBrokerClient class
- sets the reference to each instance into the inner dictionary for later retrieval

#### Methods
- `send_command(cmd, brokerclientname)`: a method responsible for routing the request to send a command to the proper BackendBrokerClient instance, looking it up in the dictionary by means of the `brokerclientname` parameter

### Main
The `Main` module must interact with each BackendBrokerClient solely via `Polyglot`.
It knows:
- the list of BackendBrokerClient that must be run
- the dict of conf parameters needed by each BackendBrokerClient to be started
- the brokerclientname (or protocol) of each device (to ask polyglot to properly route the requests)

**Comment by stefanoterna** [comment]
## TODO

- [ ] implement the interface (the mocks) of `BackendBrokerClientXmpp` and `BackendBrokerClientMqtt` (with `pass` methods)
- [ ] implement `Polyglot`
  - test it passing in the constructor the correct configuration dict and printing logs from the constructor of each BackendBrokerClient mock
- [ ] implement `BackendBrokerClientXmpp` porting the current `commander` module
  - note that currently `init` and `send_command` are module methods, they must become instance (class) methods
- [ ] refactor `main`:
  - refactor imports
  - substitute `commanded.init` with the instantiation of the `Polyglot` class, passing in the correct config dict as defined previously
  - everywhere a `commander.send_command` is referred, substitute with the `polyglot.send_command` method
    - temporarily set `brokerclientname='BackendBrokerClientXmpp'` since the BackendBrokerClientMqtt is not yet implemented
- [ ] regression test of the xmpp protocol
  - apply this same checklist: iottly/iottly-device-agent-py#10
- [ ] implement `BackendBrokerClientMqtt`
- [ ] test the mqtt implementation, 
  - changing the temporary setting `brokerclientname='BackendBrokerClientMqtt'` in main
  - run the device in interactive mode, with settings.json customized to use mqtt
  - test sending a command from the iottly front-end
    - NB: the response message will not be available in the console, since subscription is not yet implemented
